# Generated by Django 2.0.6 on 2018-06-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Product ID')),
                ('name', models.CharField(max_length=128, verbose_name='Product Name')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('modify_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
