# Generated by Django 2.0.6 on 2018-07-03 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleShop', '0003_emailmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailMessage',
            new_name='ContactMessage',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='receiver',
            new_name='receiver_email',
        ),
    ]
