# Generated by Django 2.0.6 on 2018-07-07 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleShop', '0004_auto_20180702_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='receiver_email',
            new_name='client_email',
        ),
    ]
