# Generated by Django 2.0.6 on 2018-07-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleShop', '0006_auto_20180707_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='add_comments',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Additional Comments'),
        ),
    ]
