# Generated by Django 2.0.6 on 2018-07-08 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleShop', '0007_auto_20180707_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='SimpleShop.Product'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='SimpleShop.Order'),
        ),
    ]
